---

version: '3.0'

services:

  ffl:
    build:
      args:
        NODE_ENV: production
      context: .
      dockerfile: docker/ffl.dockerfile
    links:
      - redis

  ffl-dev:
    build:
      args:
        NODE_ENV: development
      context: .
      dockerfile: docker/ffl.dockerfile
    command: npm run start
    links:
      - redis
    volumes:
      - .:/app:rw

  redis:
    image: redis:5.0.5
